-- AN ORDER CANNOT REACH THE CUSTOMER BEFORE THE SELLER HANDS IT TO THE
-- CARRIER. VIOLATIONS ARE PHYSICALLY IMPOSSIBLE AND PRODUCE NEGATIVE DELIVERY
-- DURATIONS DOWNSTREAM.
--
-- KNOWN BASELINE: 23 ROWS. WARNS BECAUSE THE SOURCE IS FROZEN; THESE ROWS ARE
-- EXCLUDED FROM DURATION METRICS BY IS_DELIVERY_MEASURABLE RATHER THAN BEING
-- DROPPED HERE, SO THEY REMAIN VISIBLE FOR AUDITING.
{{ config(severity = 'warn') }}
SELECT
    order_id,
    order_delivered_carrier_date,
    order_delivered_customer_date
FROM {{ ref('stg_olist__orders') }}
WHERE order_delivered_customer_date < order_delivered_carrier_date
